[providers]
node = "18"

[build]
cmd = 'npm run build'

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PORT = '3000'

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = ['npm ci --production']

[phases.build]
cmds = ['chmod +x start.sh']